export const USER_SIGHIN_REQUEST = "USER_SIGHIN_REQUEST";
export const USER_SIGHIN_SUCCESS = "USER_SIGHIN_SUCCESS";
export const USER_SIGHIN_FAIL = "USER_SIGHIN_FAIL";
export const USER_SIGNOUT = "USER_SIGNOUT";
